# H3 - STEP 1: collect and structure (merge) datasets

### Import libraries

In [1]:
#Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
#NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np
# Matplotlib is a plotting library for python and pyplot gives us a MatLab like plotting framework. We will use this in our plotter function to plot data.
import matplotlib.pyplot as plt
#Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics
import seaborn as sns

## Load and view data

### Indoor temperature

In [11]:
# Get the database from the DataFoundry link
df_indoor = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/Yy9PQlp3clNidmNyc0pYS1JBV1NlQ1JpbGNKWHBIQlVVMjlwQW9nOFY5UT0=", low_memory=False)
df_indoor = df_indoor[(df_indoor.participant == "H3")] # select the correct participant


# # Clean up the dataframe
df_indoor = df_indoor.drop(["device_id", "sender", "participant", "id", "recipient", "pp1", "pp2", "pp3", "activity", "Unnamed: 7"], axis='columns')
df_indoor = df_indoor.rename(columns={"Temperature": "Temperature_indoor"}, errors="raise")
# df_indoor = df_indoor.rename(columns={"ts": "Timestamp"}, errors="raise")
df_indoor = df_indoor.drop(df_indoor[df_indoor.Temperature_indoor < 0].index) ## Drop temperature values under 0
df_indoor = df_indoor.drop(df_indoor[df_indoor.Temperature_indoor > 40].index) ## Drop temperature values over ...
df_indoor['ts'] = pd.to_datetime(df_indoor['ts']) ## Turn timestamp into datetime dtype
df_indoor['ts'] = df_indoor["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_indoor = df_indoor.resample('10min', on='ts').mean().reset_index() #get one value per 10 minutes
df_indoor = df_indoor.dropna() ## drop rows with empty (NA) cells
df_indoor = df_indoor.drop_duplicates() ## Drop duplicate rowsindex_list= df_indoor2.Timestamp[(df_indoor2.Timestamp >= "2024-08-08 16:00:00") & (df_indoor2.Timestamp <= "2024-08-08 19:20:00")].index.tolist(

## Drop outliers (e.g. rogue readings, tests, when a sensor is moved)
q_low = df_indoor["Temperature_indoor"].quantile(0.01)
q_hi  = df_indoor["Temperature_indoor"].quantile(0.99)
df_indoor = df_indoor[(df_indoor["Temperature_indoor"] < q_hi) & (df_indoor["Temperature_indoor"] > q_low)]

## Get data after 22 august 18:00 since this is when the sensors were installed
df_indoor = df_indoor[(df_indoor.ts > '2024-09-06 15:00:00')]

display(df_indoor.tail())
display(df_indoor.describe())

                    ts  Temperature_indoor
36 2024-09-06 15:30:00           22.960000
37 2024-09-06 15:40:00           24.088889
38 2024-09-06 15:50:00           24.755556
39 2024-09-06 16:00:00           25.388889
40 2024-09-06 16:10:00           24.833333

                                  ts  Temperature_indoor
count                            452          452.000000
mean   2024-09-08 05:20:43.805309696           25.617149
min              2024-09-06 15:30:00           22.960000
25%              2024-09-07 10:17:30           24.969166
50%              2024-09-08 05:15:00           25.605554
75%              2024-09-09 00:22:30           26.192500
max              2024-09-09 19:50:00           27.539999
std                              NaN            0.819635

In [13]:
## Save a copy with sender name specified
df_indoor_save = df_indoor.copy()
df_indoor_save.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven/2_Research/2_CoolAI/3_Jupyter_notebooks/H3/DATA (backups)\H3_indoor1.csv", index = None)

### Outdoor temperature

In [15]:
# Get the database from the DataFoundry link
df_outdoor = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/ZlF2NCtFYmczRDREYXJEMTF6S1I1Q2c2OHYzSXNaK3FDNWprOVNmYnl4cz0=")
df_outdoor = df_outdoor[(df_outdoor.participant == "H3")] # select the correct participant

# Clean up the dataframe
df_outdoor = df_outdoor.drop(["device_id", "sender", "Unnamed: 7", "participant", "id", "recipient", "pp1", "pp2", "pp3", "activity"], axis='columns')
df_outdoor = df_outdoor.rename(columns={"Temperature": "Temperature_outdoor"}, errors="raise")
df_outdoor = df_outdoor.drop(df_outdoor[df_outdoor.Temperature_outdoor < 0].index) ## Drop temperature values under 0
df_outdoor = df_outdoor.drop(df_outdoor[df_outdoor.Temperature_outdoor > 40].index) ## Drop temperature values over 33
df_outdoor['ts'] = pd.to_datetime(df_outdoor['ts']) ## Turn timestamp into datetime dtype
df_outdoor['ts'] = df_outdoor["ts"].dt.round('h')  ##Round the datestamp column to h
# df_outdoor['Temperature_outdoor'] = np.round(df_outdoor['Temperature_outdoor'] * 10) / 10 ## round temperature to .5
df_outdoor = df_outdoor.dropna() ## drop rows with empty (NA) cells
df_outdoor = df_outdoor.drop_duplicates() ## Drop duplicate rows

## Drop outliers (e.g. rogue readings, tests, when a sensor is moved)
q_low = df_outdoor["Temperature_outdoor"].quantile(0.01)
q_hi  = df_outdoor["Temperature_outdoor"].quantile(0.99)
df_outdoor = df_outdoor[(df_outdoor["Temperature_outdoor"] < q_hi) & (df_outdoor["Temperature_outdoor"] > q_low)]

## Get data after 22 august 18:00 since this is when the sensors were installed
df_outdoor = df_outdoor[(df_outdoor.ts > '2024-09-06 15:00:00')]

display(df_outdoor.tail())
display(df_outdoor.describe())

                     ts  Temperature_outdoor
864 2024-09-16 02:00:00              13.1250
866 2024-09-16 03:00:00              12.5000
868 2024-09-16 04:00:00              11.8750
870 2024-09-16 05:00:00              11.3750
872 2024-09-16 06:00:00              10.8125

                                  ts  Temperature_outdoor
count                            194           194.000000
mean   2024-09-11 06:08:58.144329984            14.755799
min              2024-09-06 16:00:00             6.625000
25%              2024-09-09 00:15:00            10.984375
50%              2024-09-11 07:00:00            15.093750
75%              2024-09-13 09:45:00            17.609375
max              2024-09-16 06:00:00            23.875000
std                              NaN             4.141747

In [16]:
## Save a copy with sender name specified
df_outdoor_save = df_outdoor.copy()
df_outdoor_save.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven/2_Research/2_CoolAI/3_Jupyter_notebooks/H3/DATA (backups)\H3_outdoor.csv", index = None)

### Door (indoor) state

In [17]:
# Get the database from the DataFoundry link
df_door = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/S0lMV3BUZ3NjZ2lQVUJUVHlJREhSM2NxNkFGT0VscHFHY0xjdXZVTS9SST0=", low_memory=False)
df_door = df_door[(df_door.participant == "H3")] # select the correct participant

# Clean up the dataframe
df_door = df_door.drop(["Unnamed: 7", "device_id", "id", "participant", "recipient", "pp1", "pp2", "pp3", "activity"], axis='columns')
df_door.tail()

                       ts  reed sensor      sender window
4217  2024-09-11T13:02:28          1.0  HH3_door_1   open
4219  2024-09-11T13:12:42          1.0  HH3_door_1   open
4221  2024-09-11T13:20:51          1.0  HH3_door_2   open
4222  2024-09-11T13:22:35          1.0  HH3_door_1   open
4224  2024-09-11T13:30:48          1.0  HH3_door_2   open

In [21]:
# Get the database from the DataFoundry link
df_door = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/S0lMV3BUZ3NjZ2lQVUJUVHlJREhSM2NxNkFGT0VscHFHY0xjdXZVTS9SST0=", low_memory=False)
df_door = df_door[(df_door.participant == "H3")] # select the correct participant
list(df_door)

['id',
 'device_id',
 'ts',
 'activity',
 'pp1',
 'pp2',
 'pp3',
 'Unnamed: 7',
 'participant',
 'recipient',
 'reed sensor',
 'sender',
 'window']

In [28]:
# Get the database from the DataFoundry link
df_door = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/S0lMV3BUZ3NjZ2lQVUJUVHlJREhSM2NxNkFGT0VscHFHY0xjdXZVTS9SST0=", low_memory=False)
df_door = df_door[(df_door.participant == "H3")] # select the correct participant
# Clean up the dataframe
df_door = df_door.drop(["Unnamed: 7", "device_id", "id", "participant", "recipient", "pp1", "pp2", "pp3", "activity"], axis='columns')

# get the right window sensor values
df_door1 = df_door.loc[df_door['sender'] == "HH3_door_1"].copy()
df_door1 = df_door1.rename(columns={"reed sensor": "door1"}, errors="raise")
df_door1 = df_door1.drop(["sender", "window"], axis='columns')
df_door1['ts'] = pd.to_datetime(df_door1['ts']) #Turn timestamp into datetime dtype
df_door1['ts'] = df_door1["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_door1 = df_door1.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_door1  = df_door1.dropna()
df_door1 = df_door1.drop_duplicates() #Drop duplicate rows
# get the right window sensor values
df_door2 = df_door.loc[df_door['sender'] == "HH3_door_2"].copy()
df_door2 = df_door2.rename(columns={"reed sensor": "door2"}, errors="raise")
df_door2 = df_door2.drop(["sender", "window"], axis='columns')
df_door2['ts'] = pd.to_datetime(df_door2['ts']) #Turn timestamp into datetime dtype
df_door2['ts'] = df_door2["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_door2 = df_door2.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_door2  = df_door2.dropna()
df_door2 = df_door2.drop_duplicates() #Drop duplicate rows


df_door = pd.merge_asof(df_door1.sort_values('ts'), df_door2.sort_values('ts'), on='ts',tolerance =pd.Timedelta('120 min'))
df_door = df_door.drop_duplicates(subset=['ts']) #Drop duplicate rows


df_door.tail()

                     ts  door1  door2
611 2024-09-11 12:40:00    1.0    1.0
612 2024-09-11 12:50:00    1.0    1.0
613 2024-09-11 13:00:00    1.0    1.0
614 2024-09-11 13:10:00    1.0    1.0
615 2024-09-11 13:20:00    1.0    1.0

In [29]:
## Save a copy 
df_door_save = df_door.copy()
df_door_save.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven/2_Research/2_CoolAI/3_Jupyter_notebooks/H3/DATA (backups)\H3_door.csv", index = None)

### Window state

In [36]:
# Get the database from the DataFoundry link
df_window = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/QWM2TVQ4OE9KRWF1UU1tRUxzbXJFS1IxM3hhMVZORnNlSlMvRmVyZUFsdz0=", low_memory=False)
df_window = df_window[(df_window.participant == "H3")] # select the correct participant

# Clean up the dataframe
df_window = df_window.drop(["Unnamed: 7", "device_id", "id", "participant", "recipient", "pp1", "pp2", "pp3", "activity", "light", "participant", "curtain"], axis='columns')

list(df_window)

['ts', 'distance sensor', 'light sensor', 'reed sensor', 'sender', 'window']

In [42]:
# get the left window sensor values
df_window_1 = df_window.loc[(df_window['sender'] == "HH3_window_1")].copy()
df_window_1["curtain_1"] = np.where(df_window_1.loc[:,"distance sensor"] > 35, 1, 0) # set curtain state (0= closed; 1 = open)
df_window_1 = df_window_1.rename(columns={"distance sensor": "distance_1"}, errors="raise")
df_window_1["shade_1"] = np.where(df_window_1.loc[:,"light sensor"] < 2000, 1, 0) # set shade (0= no shade; 1 = yes shade)
df_window_1 = df_window_1.rename(columns={"light sensor": "light_1"}, errors="raise")
df_window_1 = df_window_1.drop(["sender", "window", "reed sensor"], axis='columns') # drop window and reed sensor since this sensor does not measure a door state
df_window_1['ts'] = pd.to_datetime(df_window_1['ts']) #Turn timestamp into datetime dtype
df_window_1['ts'] = df_window_1["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_window_1 = df_window_1.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_window_1  = df_window_1.dropna()
df_window_1 = df_window_1.drop_duplicates() #Drop duplicate rows
# # get the right window sensor values
df_window_2 = df_window.loc[df_window['sender'] == "HH3_window_2"].copy()
df_window_2["curtain_2"] = np.where(df_window_2.loc[:,"distance sensor"] > 35, 1, 0) # set curtain state (0= closed; 1 = open)
df_window_2 = df_window_2.rename(columns={"distance sensor": "distance_2"}, errors="raise")
df_window_2["shade_2"] = np.where(df_window_2.loc[:,"light sensor"] < 2000, 1, 0) # set shade (0= no shade; 1 = yes shade)
df_window_2 = df_window_2.rename(columns={"light sensor": "light_2"}, errors="raise")
df_window_2 = df_window_2.drop(["sender", "window", "reed sensor"], axis='columns') # drop window and reed sensor since this sensor does not measure a door state
df_window_2['ts'] = pd.to_datetime(df_window_2['ts']) #Turn timestamp into datetime dtype
df_window_2['ts'] = df_window_2["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_window_2 = df_window_2.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_window_2  = df_window_2.dropna()
df_window_2 = df_window_2.drop_duplicates() #Drop duplicate rows
# # get the right window sensor values
df_window_3 = df_window.loc[df_window['sender'] == "HH3_window_3"].copy()
df_window_3["curtain_3"] = np.where(df_window_3.loc[:,"distance sensor"] > 35, 1, 0) # set curtain state (0= closed; 1 = open)
df_window_3 = df_window_3.rename(columns={"distance sensor": "distance_3"}, errors="raise")
df_window_3["shade_3"] = np.where(df_window_3.loc[:,"light sensor"] < 2000, 1, 0) # set shade (0= no shade; 1 = yes shade)
df_window_3 = df_window_3.rename(columns={"light sensor": "light_3"}, errors="raise")
df_window_3 = df_window_3.drop(["sender", "window", "reed sensor"], axis='columns') # drop window and reed sensor since this sensor does not measure a door state
df_window_3['ts'] = pd.to_datetime(df_window_3['ts']) #Turn timestamp into datetime dtype
df_window_3['ts'] = df_window_3["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_window_3 = df_window_3.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_window_3  = df_window_3.dropna()
df_window_3 = df_window_3.drop_duplicates() #Drop duplicate rows


# # get the right window sensor values
df_windowdoor_1 = df_window.loc[df_window['sender'] == "HH3_windowdoor_1"].copy()
df_windowdoor_1 = df_windowdoor_1.rename(columns={"reed sensor": "windowdoor_1"}, errors="raise")
df_windowdoor_1 = df_windowdoor_1.drop(["sender", "light sensor", "window", "distance sensor"], axis='columns')
df_windowdoor_1['ts'] = pd.to_datetime(df_windowdoor_1['ts']) #Turn timestamp into datetime dtype
df_windowdoor_1['ts'] = df_windowdoor_1["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_windowdoor_1 = df_windowdoor_1.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_windowdoor_1  = df_windowdoor_1.dropna()
df_windowdoor_1 = df_windowdoor_1.drop_duplicates() #Drop duplicate rows
# # get the right window sensor values
df_windowdoor_2 = df_window.loc[df_window['sender'] == "HH3_windowdoor_2"].copy()
df_windowdoor_2 = df_windowdoor_2.rename(columns={"reed sensor": "windowdoor_2"}, errors="raise")
df_windowdoor_2 = df_windowdoor_2.drop(["sender", "light sensor", "window", "distance sensor"], axis='columns')
df_windowdoor_2['ts'] = pd.to_datetime(df_windowdoor_2['ts']) #Turn timestamp into datetime dtype
df_windowdoor_2['ts'] = df_windowdoor_2["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_windowdoor_2 = df_windowdoor_2.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_windowdoor_2  = df_windowdoor_2.dropna()
df_windowdoor_2 = df_windowdoor_2.drop_duplicates() #Drop duplicate rows
# # get the right window sensor values
df_windowdoor_3 = df_window.loc[df_window['sender'] == "HH3_windowdoor_3"].copy()
df_windowdoor_3 = df_windowdoor_3.rename(columns={"reed sensor": "windowdoor_3"}, errors="raise")
df_windowdoor_3 = df_windowdoor_3.drop(["sender", "light sensor", "window", "distance sensor"], axis='columns')
df_windowdoor_3['ts'] = pd.to_datetime(df_windowdoor_3['ts']) #Turn timestamp into datetime dtype
df_windowdoor_3['ts'] = df_windowdoor_3["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_windowdoor_3 = df_windowdoor_3.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_windowdoor_3  = df_windowdoor_3.dropna()
df_windowdoor_3 = df_windowdoor_3.drop_duplicates() #Drop duplicate rows



df_window_merge1 = pd.merge_asof(df_window_1.sort_values('ts'), df_window_2.sort_values('ts'), on='ts',tolerance =pd.Timedelta('120 min'))
df_window_merge2 = pd.merge_asof(df_window_3.sort_values('ts'), df_window_merge1.sort_values('ts'), on='ts',tolerance =pd.Timedelta('120 min'))
df_windowdoor_merge1 = pd.merge_asof(df_windowdoor_1.sort_values('ts'), df_windowdoor_2.sort_values('ts'), on='ts',tolerance =pd.Timedelta('120 min'))
df_windowdoor_merge2 = pd.merge_asof(df_windowdoor_3.sort_values('ts'), df_windowdoor_merge1.sort_values('ts'), on='ts',tolerance =pd.Timedelta('120 min'))
df_window = pd.merge_asof(df_window_merge2.sort_values('ts'), df_windowdoor_merge2.sort_values('ts'), on='ts',tolerance =pd.Timedelta('120 min'))
df_window = df_window.drop_duplicates(subset=['ts']) #Drop duplicate rows

display(df_window.tail())
display(df_window.describe())

,ts,distance_3,light_3,curtain_3,shade_3,distance_1,light_1,curtain_1,shade_1,distance_2,light_2,curtain_2,shade_2,windowdoor_3,windowdoor_1,windowdoor_2
623,2024-09-11 12:20:00,1.0,1665.0,0.0,1.0,798.0,1931.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0
624,2024-09-11 12:30:00,1.0,1157.0,0.0,1.0,798.0,1935.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0
625,2024-09-11 12:50:00,3.0,272.0,0.0,1.0,798.0,788.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0
626,2024-09-11 13:10:00,3.0,414.0,0.0,1.0,2.0,118.0,0.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,0.0
627,2024-09-11 13:20:00,3.0,0.0,0.0,1.0,2.0,118.0,0.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,0.0

,ts,distance_3,light_3,curtain_3,shade_3,distance_1,light_1,curtain_1,shade_1,distance_2,light_2,curtain_2,shade_2,windowdoor_3,windowdoor_1,windowdoor_2
count,628,628.000000,628.000000,628.000000,628.000000,628.000000,628.000000,628.000000,628.000000,535.000000,535.000000,535.000000,535.000000,628.000000,628.000000,628.000000
mean,2024-09-09 01:47:05.159235840,144.928344,754.194268,0.651274,0.848726,303.065287,816.700637,0.859873,0.799363,142.968224,748.231776,0.656075,0.857944,0.457006,0.992038,0.996815
min,2024-09-06 14:10:00,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2024-09-07 20:07:30,1.000000,0.000000,0.000000,1.000000,38.000000,0.000000,1.000000,1.000000,9.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000
50%,2024-09-09 01:45:00,186.500000,0.000000,1.000000,1.000000,49.000000,0.000000,1.000000,1.000000,104.000000,64.000000,1.000000,1.000000,0.000000,1.000000,1.000000
75%,2024-09-10 07:22:30,246.000000,1444.750000,1.000000,1.000000,798.000000,1847.000000,1.000000,1.000000,104.000000,1405.500000,1.000000,1.000000,1.000000,1.000000,1.000000
max,2024-09-11 13:20:00,802.000000,3861.000000,1.000000,1.000000,799.000000,3337.000000,1.000000,1.000000,799.000000,3699.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,NaN,113.587756,1003.931684,0.476947,0.358601,357.527546,988.697406,0.347396,0.400796,229.000223,956.531215,0.475461,0.349434,0.498545,0.088944,0.056388

In [43]:
## Save a copy 
df_window_save = df_window.copy()
df_window_save.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven/2_Research/2_CoolAI/3_Jupyter_notebooks/H3/DATA (backups)\H3_window.csv", index = None)

### API weather data (outdoor temperature)

In [44]:
# Get the database from the DataFoundry link
df_API = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/N0FsN2loZlVYMWhBaE0rd0l5T2NadzR3YTNBcnovQlJ0SG13dHMxL0U1RT0=")
df_API = df_API[(df_API.participant == "H3")] # select the correct participant

# Clean up the dataframe
df_API = df_API.drop(["id", "participant", "sender", "device_id", "activity", "pp1", "pp2", "pp3", "Unnamed: 7", "recipient"], axis='columns')
df_API['Temperature_API'] = np.round(df_API['Temperature_API'] * 10) / 10 # round temperature to 1 decimal
df_API['Temperature_API_MIN'] = np.round(df_API['Temperature_API_MIN'] * 10) / 10 # round temperature to 1 decimal
df_API['Temperature_API_MAX'] = np.round(df_API['Temperature_API_MAX'] * 10) / 10 # round temperature to 1 decimal
df_API['ts'] = pd.to_datetime(df_API['ts']) # Turn timestamp into datetime dtype
df_API['ts'] = df_API["ts"].dt.round('min')  # Round the datestamp column to minutes
df_API = df_API.resample('10min', on='ts').first().reset_index() #get one value per 10 minutes
df_API = df_API.drop_duplicates() # Drop duplicate rows
df_API = df_API.dropna() # drop rows with empty (NA) cells

## Drop outliers (e.g. rogue readings, tests, when a sensor is moved)
q_low = df_API["Temperature_API"].quantile(0.01)
q_hi  = df_API["Temperature_API"].quantile(0.99)
df_API = df_API[(df_API["Temperature_API"] < q_hi) & (df_API["Temperature_API"] > q_low)]

# Get data after 22 august 18:00 since this is when the sensors were installed
df_API = df_API[(df_API.ts > '2024-09-06 15:00:00')]

display(df_API.tail())
display(df_API.describe())

,ts,Temperature_API,Temperature_API_MAX,Temperature_API_MIN,weather_description,weather_main
490,2024-09-09 19:10:00,17.9,19.0,16.6,scattered clouds,Clouds
491,2024-09-09 19:20:00,17.6,18.8,16.1,scattered clouds,Clouds
492,2024-09-09 19:30:00,17.4,18.4,16.1,scattered clouds,Clouds
493,2024-09-09 19:40:00,17.1,18.0,16.0,scattered clouds,Clouds
494,2024-09-09 19:50:00,17.1,17.8,16.0,scattered clouds,Clouds

,ts,Temperature_API,Temperature_API_MAX,Temperature_API_MIN
count,441,441.000000,441.000000,441.000000
mean,2024-09-08 05:05:06.122449152,19.185034,20.320181,17.944444
min,2024-09-06 15:20:00,15.300000,16.000000,13.500000
25%,2024-09-07 09:40:00,17.100000,18.200000,15.700000
50%,2024-09-08 05:00:00,18.800000,20.000000,17.700000
75%,2024-09-08 23:40:00,20.500000,21.700000,19.300000
max,2024-09-09 19:50:00,27.000000,28.800000,25.500000
std,NaN,2.849179,2.953184,2.819651

## MERGE ON TIMESTAMP

In [45]:
### merge the window dataframes on the timestamps for the last 72 hours
from functools import reduce
# Create a list of DataFrames to merge
dataframes_to_merge = [
    df_indoor,
    df_API,
    df_window,
    df_outdoor,
    df_door,
]

# Function to merge two DataFrames
def merge_asof(df1, df2):
    return pd.merge_asof(df1.sort_values('ts'), df2.sort_values('ts'), on='ts', tolerance=pd.Timedelta('120 min'))

# Use reduce to merge all DataFrames in one go
df_merge = reduce(merge_asof, dataframes_to_merge)
df_merge.tail()

,ts,Temperature_indoor,Temperature_API,Temperature_API_MAX,Temperature_API_MIN,weather_description,weather_main,distance_3,light_3,curtain_3,...,distance_2,light_2,curtain_2,shade_2,windowdoor_3,windowdoor_1,windowdoor_2,Temperature_outdoor,door1,door2
447,2024-09-09 19:10:00,24.930000,17.9,19.0,16.6,scattered clouds,Clouds,246.0,1043.0,1.0,...,798.0,67.0,1.0,1.0,0.0,1.0,1.0,18.4375,1.0,1.0
448,2024-09-09 19:20:00,25.044444,17.6,18.8,16.1,scattered clouds,Clouds,166.0,0.0,1.0,...,798.0,67.0,1.0,1.0,1.0,1.0,1.0,18.4375,1.0,1.0
449,2024-09-09 19:30:00,25.099998,17.4,18.4,16.1,scattered clouds,Clouds,3.0,0.0,0.0,...,3.0,0.0,0.0,1.0,1.0,1.0,1.0,18.4375,1.0,1.0
450,2024-09-09 19:40:00,25.099998,17.1,18.0,16.0,scattered clouds,Clouds,3.0,0.0,0.0,...,3.0,0.0,0.0,1.0,1.0,1.0,1.0,18.4375,1.0,1.0
451,2024-09-09 19:50:00,25.099998,17.1,17.8,16.0,scattered clouds,Clouds,3.0,0.0,0.0,...,2.0,0.0,0.0,1.0,1.0,1.0,1.0,18.4375,1.0,1.0

In [46]:
df_merge['hr'] = df_merge['ts'].dt.hour
df_merge['date'] = df_merge['ts'].dt.date

## SAVE AS CSV

In [28]:
df_merge.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\Year4_CoolAI\Jupyter_notebooks\H2\DATA (backups)\1_merged.csv", index = None)