# HH2 - STEP 1: collect and structure (merge) datasets

### Import libraries

In [7]:
#Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
#NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np
# Matplotlib is a plotting library for python and pyplot gives us a MatLab like plotting framework. We will use this in our plotter function to plot data.
import matplotlib.pyplot as plt
#Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics
import seaborn as sns

## Load and view data

### Indoor temperature

In [10]:
# Get the database from the DataFoundry link
df_indoor = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/Yy9PQlp3clNidmNyc0pYS1JBV1NlQ1JpbGNKWHBIQlVVMjlwQW9nOFY5UT0=", low_memory=False)
df_indoor = df_indoor[(df_indoor.participant == "H2")] # select the correct participant


# # Clean up the dataframe
df_indoor = df_indoor.drop(["device_id", "sender", "participant", "id", "recipient", "pp1", "pp2", "pp3", "activity", "Unnamed: 7"], axis='columns')
df_indoor = df_indoor.rename(columns={"Temperature": "Temperature_indoor"}, errors="raise")
# df_indoor = df_indoor.rename(columns={"ts": "Timestamp"}, errors="raise")
df_indoor = df_indoor.drop(df_indoor[df_indoor.Temperature_indoor < 0].index) ## Drop temperature values under 0
df_indoor = df_indoor.drop(df_indoor[df_indoor.Temperature_indoor > 40].index) ## Drop temperature values over ...
df_indoor['ts'] = pd.to_datetime(df_indoor['ts']) ## Turn timestamp into datetime dtype
df_indoor['ts'] = df_indoor["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_indoor = df_indoor.resample('10min', on='ts').mean().reset_index() #get one value per 10 minutes
df_indoor = df_indoor.dropna() ## drop rows with empty (NA) cells
df_indoor = df_indoor.drop_duplicates() ## Drop duplicate rowsindex_list= df_indoor2.Timestamp[(df_indoor2.Timestamp >= "2024-08-08 16:00:00") & (df_indoor2.Timestamp <= "2024-08-08 19:20:00")].index.tolist(

## Drop outliers (e.g. rogue readings, tests, when a sensor is moved)
q_low = df_indoor["Temperature_indoor"].quantile(0.01)
q_hi  = df_indoor["Temperature_indoor"].quantile(0.99)
df_indoor = df_indoor[(df_indoor["Temperature_indoor"] < q_hi) & (df_indoor["Temperature_indoor"] > q_low)]

## Get data after 22 august 18:00 since this is when the sensors were installed
df_indoor = df_indoor[(df_indoor.ts > '2024-08-28 16:00:00')]

display(df_indoor.tail())
display(df_indoor.describe())

                      ts  Temperature_indoor
4849 2024-10-01 00:50:00           19.290000
4850 2024-10-01 01:00:00           19.220000
4851 2024-10-01 01:10:00           19.260000
4852 2024-10-01 01:20:00           19.300000
4853 2024-10-01 01:30:00           19.244444

                                  ts  Temperature_indoor
count                           4744         4744.000000
mean   2024-09-14 12:06:00.834738432           23.351288
min              2024-08-28 17:10:00           19.210000
25%              2024-09-06 06:37:30           21.940000
50%              2024-09-14 12:35:00           23.197222
75%              2024-09-22 19:02:30           24.628497
max              2024-10-01 01:30:00           28.190000
std                              NaN            1.916944

In [11]:
## Save a copy with sender name specified
df_indoor_save = df_indoor.copy()
df_indoor_save.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\Year4_CoolAI\Jupyter_notebooks\H2\DATA (backups)\HH2_indoor1.csv", index = None)

### Outdoor temperature

In [13]:
# Get the database from the DataFoundry link
df_outdoor = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/ZlF2NCtFYmczRDREYXJEMTF6S1I1Q2c2OHYzSXNaK3FDNWprOVNmYnl4cz0=")
df_outdoor = df_outdoor[(df_outdoor.participant == "H2")] # select the correct participant

# Clean up the dataframe
df_outdoor = df_outdoor.drop(["device_id", "sender", "Unnamed: 7", "participant", "id", "recipient", "pp1", "pp2", "pp3", "activity"], axis='columns')
df_outdoor = df_outdoor.rename(columns={"Temperature": "Temperature_outdoor"}, errors="raise")
df_outdoor = df_outdoor.drop(df_outdoor[df_outdoor.Temperature_outdoor < 0].index) ## Drop temperature values under 0
df_outdoor = df_outdoor.drop(df_outdoor[df_outdoor.Temperature_outdoor > 40].index) ## Drop temperature values over 33
df_outdoor['ts'] = pd.to_datetime(df_outdoor['ts']) ## Turn timestamp into datetime dtype
df_outdoor['ts'] = df_outdoor["ts"].dt.round('h')  ##Round the datestamp column to h
# df_outdoor['Temperature_outdoor'] = np.round(df_outdoor['Temperature_outdoor'] * 10) / 10 ## round temperature to .5
df_outdoor = df_outdoor.dropna() ## drop rows with empty (NA) cells
df_outdoor = df_outdoor.drop_duplicates() ## Drop duplicate rows

## Drop outliers (e.g. rogue readings, tests, when a sensor is moved)
q_low = df_outdoor["Temperature_outdoor"].quantile(0.01)
q_hi  = df_outdoor["Temperature_outdoor"].quantile(0.99)
df_outdoor = df_outdoor[(df_outdoor["Temperature_outdoor"] < q_hi) & (df_outdoor["Temperature_outdoor"] > q_low)]

## Get data after 22 august 18:00 since this is when the sensors were installed
df_outdoor = df_outdoor[(df_outdoor.ts > '2024-08-28 16:00:00')]

display(df_outdoor.tail())
display(df_outdoor.describe())

                      ts  Temperature_outdoor
1237 2024-10-01 05:00:00              13.0625
1238 2024-10-01 06:00:00              11.9375
1239 2024-10-01 07:00:00              11.8125
1240 2024-10-01 08:00:00              11.8125
1241 2024-10-01 09:00:00              12.0000

                                  ts  Temperature_outdoor
count                            793           793.000000
mean   2024-09-14 17:36:41.765447680            18.243695
min              2024-08-28 17:00:00             6.750000
25%              2024-09-06 13:00:00            14.375000
50%              2024-09-14 21:00:00            17.937500
75%              2024-09-23 00:00:00            21.812500
max              2024-10-01 09:00:00            34.500000
std                              NaN             5.434432

In [14]:
## Save a copy with sender name specified
df_outdoor_save = df_outdoor.copy()
df_outdoor_save.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\Year4_CoolAI\Jupyter_notebooks\H2\DATA (backups)\HH2_outdoor.csv", index = None)

### Door (indoor) state

In [16]:
# Get the database from the DataFoundry link
df_door = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/S0lMV3BUZ3NjZ2lQVUJUVHlJREhSM2NxNkFGT0VscHFHY0xjdXZVTS9SST0=", low_memory=False)
df_door = df_door[(df_door.participant == "H2")] # select the correct participant

# Clean up the dataframe
df_door = df_door.drop(["Unnamed: 7", "device_id", "id", "participant", "recipient", "pp1", "pp2", "pp3", "activity"], axis='columns')
df_door.tail()

                       ts  reed sensor      sender  window
7002  2024-10-01T08:36:01          0.0  HH2_door_1  closed
7003  2024-10-01T08:45:57          0.0  HH2_door_1  closed
7004  2024-10-01T08:55:52          0.0  HH2_door_1  closed
7005  2024-10-01T09:05:48          0.0  HH2_door_1  closed
7006  2024-10-01T09:15:45          0.0  HH2_door_1  closed

In [17]:
# Get the database from the DataFoundry link
df_door = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/S0lMV3BUZ3NjZ2lQVUJUVHlJREhSM2NxNkFGT0VscHFHY0xjdXZVTS9SST0=", low_memory=False)
df_door = df_door[(df_door.participant == "H2")] # select the correct participant
# Clean up the dataframe
df_door = df_door.drop(["Unnamed: 7", "device_id", "id", "participant", "recipient", "pp1", "pp2", "pp3", "activity"], axis='columns')

# # get the right window sensor values
df_door = df_door.loc[df_door['sender'] == "HH2_door_1"].copy()
df_door = df_door.rename(columns={"reed sensor": "door"}, errors="raise")
df_door = df_door.drop(["sender", "window"], axis='columns')
df_door['ts'] = pd.to_datetime(df_door['ts']) #Turn timestamp into datetime dtype
df_door['ts'] = df_door["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_door = df_door.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_door  = df_door.dropna()
df_door = df_door.drop_duplicates() #Drop duplicate rows
df_door.tail()

                      ts  door
4861 2024-10-01 08:30:00   0.0
4862 2024-10-01 08:40:00   0.0
4863 2024-10-01 08:50:00   0.0
4864 2024-10-01 09:00:00   0.0
4865 2024-10-01 09:10:00   0.0

In [18]:
## Save a copy 
df_door = df_door.copy()
df_door.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\Year4_CoolAI\Jupyter_notebooks\H2\DATA (backups)\HH2_door.csv", index = None)

### Window state

In [45]:
# Get the database from the DataFoundry link
df_window = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/QWM2TVQ4OE9KRWF1UU1tRUxzbXJFS1IxM3hhMVZORnNlSlMvRmVyZUFsdz0=", low_memory=False)
df_window = df_window[(df_window.participant == "H2")] # select the correct participant

# Clean up the dataframe
df_window = df_window.drop(["Unnamed: 7", "device_id", "id", "participant", "recipient", "pp1", "pp2", "pp3", "activity", "light", "participant", "curtain"], axis='columns')

# get the left window sensor values
df_window_left = df_window.loc[(df_window['sender'] == "HH2_window_1") | (df_window['sender'] == "HH2_window_1_V2")].copy()
df_window_left["curtain_left"] = np.where(df_window_left.loc[:,"distance sensor"] > 35, 1, 0) # set curtain state (0= closed; 1 = open)
df_window_left = df_window_left.rename(columns={"distance sensor": "distance_left"}, errors="raise")
df_window_left["shade_left"] = np.where(df_window_left.loc[:,"light sensor"] < 2000, 1, 0) # set shade (0= no shade; 1 = yes shade)
df_window_left = df_window_left.rename(columns={"light sensor": "light_left"}, errors="raise")
df_window_left = df_window_left.drop(["sender", "window", "reed sensor"], axis='columns') # drop window and reed sensor since this sensor does not measure a door state
df_window_left['ts'] = pd.to_datetime(df_window_left['ts']) #Turn timestamp into datetime dtype
df_window_left['ts'] = df_window_left["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_window_left = df_window_left.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_window_left  = df_window_left.dropna()
df_window_left = df_window_left.drop_duplicates() #Drop duplicate rows

# # get the right window sensor values
df_window_right = df_window.loc[df_window['sender'] == "HH2_window_2"].copy()
df_window_right["curtain_right"] = np.where(df_window_right.loc[:,"distance sensor"] > 35, 1, 0) # set curtain state (0= closed; 1 = open)
df_window_right = df_window_right.rename(columns={"distance sensor": "distance_right"}, errors="raise")
df_window_right["shade_right"] = np.where(df_window_right.loc[:,"light sensor"] < 2000, 1, 0) # set shade (0= no shade; 1 = yes shade)
df_window_right = df_window_right.rename(columns={"light sensor": "light_right"}, errors="raise")
df_window_right = df_window_right.drop(["sender", "window", "reed sensor"], axis='columns') # drop window and reed sensor since this sensor does not measure a door state
df_window_right['ts'] = pd.to_datetime(df_window_right['ts']) #Turn timestamp into datetime dtype
df_window_right['ts'] = df_window_right["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_window_right = df_window_right.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_window_right  = df_window_right.dropna()
df_window_right = df_window_right.drop_duplicates() #Drop duplicate rows


# # get the right window sensor values
df_window_door = df_window.loc[df_window['sender'] == "HH2_windowdoor_1"].copy()
df_window_door = df_window_door.rename(columns={"reed sensor": "window_door"}, errors="raise")
df_window_door = df_window_door.drop(["sender", "light sensor", "window", "distance sensor"], axis='columns')
df_window_door['ts'] = pd.to_datetime(df_window_door['ts']) #Turn timestamp into datetime dtype
df_window_door['ts'] = df_window_door["ts"].dt.round('min')  ##Round the datestamp column to minutes
df_window_door = df_window_door.resample('10min', on='ts').last().reset_index() #get one value per 10 minutes
df_window_door  = df_window_door.dropna()
df_window_door = df_window_door.drop_duplicates() #Drop duplicate rows


df_window_merge1 = pd.merge_asof(df_window_right.sort_values('ts'), df_window_left.sort_values('ts'), on='ts',tolerance =pd.Timedelta('120 min'))
df_window = pd.merge_asof(df_window_door.sort_values('ts'), df_window_merge1.sort_values('ts'), on='ts',tolerance =pd.Timedelta('120 min'))
df_window = df_window.drop_duplicates(subset=['ts']) #Drop duplicate rows

display(df_window.tail())
display(df_window.describe())

,ts,window_door,distance_right,light_right,curtain_right,shade_right,distance_left,light_left,curtain_left,shade_left
4321,2024-10-01 10:00:00,0.0,37.0,2038.0,1.0,0.0,NaN,NaN,NaN,NaN
4322,2024-10-01 10:10:00,0.0,44.0,2559.0,1.0,0.0,NaN,NaN,NaN,NaN
4323,2024-10-01 10:20:00,0.0,39.0,2514.0,1.0,0.0,NaN,NaN,NaN,NaN
4324,2024-10-01 10:30:00,0.0,45.0,2096.0,1.0,0.0,NaN,NaN,NaN,NaN
4325,2024-10-01 10:40:00,0.0,44.0,2279.0,1.0,0.0,NaN,NaN,NaN,NaN

,ts,window_door,distance_right,light_right,curtain_right,shade_right,distance_left,light_left,curtain_left,shade_left
count,4326,4326.000000,4326.000000,4326.000000,4326.000000,4326.000000,3533.000000,3533.000000,3533.000000,3533.000000
mean,2024-09-15 03:27:13.564493824,0.217753,152.854831,1250.123209,0.577439,0.649330,172.071327,1359.653552,0.521653,0.616190
min,2024-08-28 14:30:00,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2024-09-07 07:12:30,0.000000,14.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000
50%,2024-09-15 16:35:00,0.000000,50.000000,249.500000,1.000000,1.000000,53.000000,166.000000,1.000000,1.000000
75%,2024-09-23 13:37:30,0.000000,222.000000,2559.000000,1.000000,1.000000,238.000000,2929.000000,1.000000,1.000000
max,2024-10-01 10:40:00,1.000000,801.000000,4001.000000,1.000000,1.000000,803.000000,4095.000000,1.000000,1.000000
std,NaN,0.412766,200.200691,1430.193602,0.494024,0.477235,232.374594,1546.049534,0.499602,0.486381

In [21]:
## Save a copy 
df_window_save = df_window.copy()
df_window_save.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\Year4_CoolAI\Jupyter_notebooks\H2\DATA (backups)\HH2_window.csv", index = None)

### API weather data (outdoor temperature)

In [23]:
# Get the database from the DataFoundry link
df_API = pd.read_csv (r"https://data.id.tue.nl/datasets/downloadPublic/N0FsN2loZlVYMWhBaE0rd0l5T2NadzR3YTNBcnovQlJ0SG13dHMxL0U1RT0=")
df_API = df_API[(df_API.participant == "H2")] # select the correct participant

# Clean up the dataframe
df_API = df_API.drop(["id", "participant", "sender", "device_id", "activity", "pp1", "pp2", "pp3", "Unnamed: 7", "recipient"], axis='columns')
df_API['Temperature_API'] = np.round(df_API['Temperature_API'] * 10) / 10 # round temperature to 1 decimal
df_API['Temperature_API_MIN'] = np.round(df_API['Temperature_API_MIN'] * 10) / 10 # round temperature to 1 decimal
df_API['Temperature_API_MAX'] = np.round(df_API['Temperature_API_MAX'] * 10) / 10 # round temperature to 1 decimal
df_API['ts'] = pd.to_datetime(df_API['ts']) # Turn timestamp into datetime dtype
df_API['ts'] = df_API["ts"].dt.round('min')  # Round the datestamp column to minutes
df_API = df_API.resample('10min', on='ts').first().reset_index() #get one value per 10 minutes
df_API = df_API.drop_duplicates() # Drop duplicate rows
df_API = df_API.dropna() # drop rows with empty (NA) cells

## Drop outliers (e.g. rogue readings, tests, when a sensor is moved)
q_low = df_API["Temperature_API"].quantile(0.01)
q_hi  = df_API["Temperature_API"].quantile(0.99)
df_API = df_API[(df_API["Temperature_API"] < q_hi) & (df_API["Temperature_API"] > q_low)]

# Get data after 22 august 18:00 since this is when the sensors were installed
df_API = df_API[(df_API.ts > '2024-08-28 16:00:00')]

display(df_API.tail())
display(df_API.describe())

,ts,Temperature_API,Temperature_API_MAX,Temperature_API_MIN,weather_description,weather_main
4896,2024-10-01 08:40:00,12.0,12.7,11.5,overcast clouds,Clouds
4897,2024-10-01 08:50:00,12.0,12.7,11.5,overcast clouds,Clouds
4898,2024-10-01 09:00:00,12.0,12.7,11.5,overcast clouds,Clouds
4899,2024-10-01 09:10:00,12.1,13.0,11.5,overcast clouds,Clouds
4900,2024-10-01 09:20:00,12.1,13.0,11.5,overcast clouds,Clouds

,ts,Temperature_API,Temperature_API_MAX,Temperature_API_MIN
count,4734,4734.000000,4734.000000,4734.000000
mean,2024-09-14 13:10:38.403042048,16.344782,17.469814,15.212400
min,2024-08-28 18:50:00,5.800000,7.100000,4.000000
25%,2024-09-06 06:52:30,13.500000,14.400000,12.600000
50%,2024-09-14 14:05:00,16.200000,17.200000,15.400000
75%,2024-09-22 20:37:30,19.300000,20.400000,18.000000
max,2024-10-01 09:20:00,29.100000,30.000000,28.200000
std,NaN,4.476549,4.521907,4.427151

## MERGE ON TIMESTAMP

In [25]:
### merge the window dataframes on the timestamps for the last 72 hours
from functools import reduce
# Create a list of DataFrames to merge
dataframes_to_merge = [
    df_indoor,
    df_API,
    df_window,
    df_outdoor,
    df_door,
]

# Function to merge two DataFrames
def merge_asof(df1, df2):
    return pd.merge_asof(df1.sort_values('ts'), df2.sort_values('ts'), on='ts', tolerance=pd.Timedelta('120 min'))

# Use reduce to merge all DataFrames in one go
df_merge = reduce(merge_asof, dataframes_to_merge)
df_merge.tail()

,ts,Temperature_indoor,Temperature_API,Temperature_API_MAX,Temperature_API_MIN,weather_description,weather_main,window_door,distance_right,light_right,curtain_right,shade_right,distance_left,light_left,curtain_left,shade_left,Temperature_outdoor,door
4739,2024-10-01 00:50:00,19.290000,13.8,14.4,12.9,overcast clouds,Clouds,0.0,38.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,13.3750,0.0
4740,2024-10-01 01:00:00,19.220000,13.7,14.4,13.1,overcast clouds,Clouds,0.0,39.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,13.1875,0.0
4741,2024-10-01 01:10:00,19.260000,13.8,14.4,12.8,overcast clouds,Clouds,0.0,39.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,13.1875,0.0
4742,2024-10-01 01:20:00,19.300000,13.8,14.4,12.8,overcast clouds,Clouds,0.0,38.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,13.1875,0.0
4743,2024-10-01 01:30:00,19.244444,13.6,14.4,12.8,overcast clouds,Clouds,0.0,38.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,13.1875,0.0

In [26]:
df_merge['hr'] = df_merge['ts'].dt.hour
df_merge['date'] = df_merge['ts'].dt.date

## SAVE AS CSV

In [28]:
df_merge.to_csv(r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\Year4_CoolAI\Jupyter_notebooks\H2\DATA (backups)\1_merged.csv", index = None)